### ISSUE TITLE
Maven folder struktura

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim5#26]
Vaš projekat ne prati standardnu maven folder strukturu:
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

dakle:
src/main/java
src/main/resources
src/test/java

Popravite ovo.
Pokušajte kreirati novi projekt kao što je opisano u tutorijalu 4 i ubaciti source files u njega.

**Comment by ghost** [comment]
Popravio sam  to, međutim nema mi foldera src/main/resources, u Efective POM stoji da je tu.
