### ISSUE TITLE
Povećanje početne forme

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#28]
Komponenta: Prijava

commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Dizajn forme nije prilagođen različitim veličinama, ukoliko se poveća daje utisak drugačije login forme.

Screenshot:
http://prntscr.com/79v5z7

Koraci za reproduciranje problema:
1.  Pokrenuti aplikaciju
2.  Kliknuti na maximize button ili razvući formu

**Comment by ghost** [comment]
Ispravljeno

Commit: 56c7c79
