### ISSUE TITLE
Istovremeno zatvaranje formi Promjena lozinke i Prijava 

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#29]
Komponenta: Promjena lozinke
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema: 
Zatvaranjem forme za promjenu lozinke zatvara se i forma prijave, što dosta zbunjuje korisnika te može praviti i problem ukoliko je korisnik znatiželjan, a nije zaboravio lozinku.

Screenshot ovakvih grešaka nije moguć zbog samog zatvaranja, odnosno nemogućnosti da se bilo šta uslika nakon što se sve ugasi.

Koraci za reproduciranje problema:
1.  Pokrenuti aplikaciju
2.  Izabrati opciju "Zaboravili ste lozinku?"
3.  Ugasiti formu Promjena lozinke

**Comment by ghost** [comment]
Ispravljano

Commit: 6086920
