### ISSUE TITLE
Promjena lozinke

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#30]
Komponenta: Prijava
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Prelaskom mišem preko opcije „Zaboravili ste lozinku?“ ne daje se osjećaj bilo kakvog daljnjeg preusmjeravanja, tj. nejasno je da li se radi samo o natpisu ili o linku koji vodi na sljedeću formu.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2. Izabrati opciju „Zaboravili ste lozinku?“

**Comment by ghost** [comment]
Ispravljeno 
Commit: 6cee483

MorRel 'vako mlada http://pokit.org/get/?6ca668a2902b4579cceec223815c67a2.jpg ?
