### ISSUE TITLE
Istovremeno zatvaranje forme Blagajna i Promjena lozinke

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#31]
Komponenta: Promjena lozinke
  commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Zatvaranjem forme za promjenu lozinke zatvara se čitava aplikacija, tj. forma Blagajna

Koraci za reproduciranje problema:
1.  Pokrenuti aplikaciju sa korisničkim imenom: Admin, te šifrom: Admin123
2.  Izabrati meni "File"
3.  Izabrati opciju "Promijeni lozinku"
4.  Zatvoriti formu Promjena lozinke

**Comment by ghost** [comment]
Ispravljeno 
Commit: 6086920
