### ISSUE TITLE
Zatvaranje forme "Uplate"

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#32]
Komponenta: Uplate
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema: Zatvarnjem forme "Uplate" zatvaraju se sve forme aplikacije

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju sa korisničkim imenom: Admin, te šifrom: Admin123
2.Izabrati studenta sa ponuđene liste na ekranu
3.Izabrati opciju "Uplate"
4.Zatvoriti formu "Uplate"

**Comment by ghost** [comment]
Ispravljano
Commit: 6086920
