### ISSUE TITLE
Istovremeno zatvaranje formi aplikacije

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#33]
Komponenta: Blagajna 
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema: 
Zatvaranjem formi koje se otvaraju kao „podforme“ na formi Blagajna zatvara se čitava aplikacija. Zbog više uočenih grešaka ovog tipa, u jednom issue navedene su forme koje ranije nisu pomenute, a čijim se zatvaranjem gasi čitava aplikacija.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa korisničkim imenom: Admin, te šifrom: Admin123
2.  Klik na meni "Dodaj" pa na opciju "Dodaj studenta" - Komponenta: “ Unos studenta “
3.  Na glavnoj formi „Blagajna“ odabirom opcije „Detalji/Uredi“ - Komponenta: Unos studenta
4.  Na glavnoj formi „Blagajna“ odabirom menija „Izvještaji“ te opcije „Generiši izvještaj“-  Komponenta:" Unos studenta"

**Comment by ghost** [comment]
Ispravljeno
commit: 6086920
