### ISSUE TITLE
Uređivanje podataka korisnika (Admin)

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#34]
Komponenta: Korisnici
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Ukoliko se odabere opcija "Detalji/Uredi" na formi Korisnici, a prethodno se ne selektuje korisnik ništa se ne dešava, izgleda kao da nije implementirano.

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
     2.Izabrati meni Uredi
     3.Izabrati podmeni Uredi korisnike
     4. Odabrati opciju „Detalji/Uredi“

Očekivani rezultat:
-Očekuje se poruka o obaveznom izboru korisnika prije njegovog uređivanja.

**Comment by dinohurem** [comment]
Ispravljeno u commit-u 6de9ebf1b9d36043b0193ba9c404d2b900752875.
