### ISSUE TITLE
Manipulacija formom Korisnici

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#35]
Komponenta: Korisnici
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Ukoliko zatvori forma Korisnici, manja forma Unos korisnika ostaje otvorena.

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
     2.Izabrati meni Uredi
     3.Izabrati podmeni "Uredi korisnike"
     4. Odabrati opciju „Dodaj“
     5. Zatvoriti formu „Korisnici“

Screenshot pri otvaranju:
http://prntscr.com/79vigh
Screenshot pri zatvaranju:
http://prntscr.com/79viky

Očekivani rezultat:
-Očekivano je da se formom „Korisnici“ ne može manipulirati dok se ne zatvori forma „Uredi korisnika“

**Comment by ghost** [comment]
To treba tako da bude!
