### ISSUE TITLE
Unos već postojećeg korisnika

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#36]
Komponenta: Unos korisnika
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Prilikom unosa korisnika sa podacima koji su već uneseni u sistem, tj. unosom istog korisnika još jednom nakon potvrde da je korisnik uspješno unesen u sistem, javlja se više novih poruka sa sljedećim sadržajem: „Could not execute statement“. 

Screenshot:
http://prntscr.com/79vjs7

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
     2.Izabrati meni Uredi
     3.Izabrati podmeni Uredi korisnike
     4. Izabrati opciju „Dodaj“
     5. Popuniti formu tačnim podacima koji su već uneseni u bazu u vidu jednog korisnika
     6. Izabrati opciju Korisnik 
     7. Izabrati opciju „Dodaj“
     8. Izabrati opciju „Dodaj“

**Comment by dinohurem** [comment]
Popravljeno u commit-u 76fb48feeb07a7b19b29b5b1ef0fa2a73beb32e9.
