### ISSUE TITLE
Reset polja za Unos korisnika

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#37]
Komponenta: Unos korisnika
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Prilikom potvrde o uspješnom unosu korisnika, forma za unos ostaje popunjena starim vrijednostima podataka, te ukoliko se unosi novi korisnik potrebno je „ručno“ brisati podatke sa forme.

Screenshot:
http://prntscr.com/79vkzw

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
     2.Izabrati meni Uredi
     3.Izabrati podmeni Uredi korisnike
     4. Selektovati opciju „Dodaj“
     5. Popuniti formu tačnim podacima
     6. Izabrati opciju Korisnik 
     7. Izabrati opciju „Dodaj“

**Comment by dinohurem** [comment]
Popravljeno u commit-u 76fb48feeb07a7b19b29b5b1ef0fa2a73beb32e9.
