### ISSUE TITLE
Nemogućnost unosa 2 imena/prezimena

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#38]
Komponenta: Unos korisnika
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Prilikom unosa prezimena nije ostavljena mogućnost unosa osoba sa 2 prezimena, te isto važi i za polje ime.

Screenshot: http://prntscr.com/79vmqr, http://prntscr.com/79vmvv

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
     2.Izabrati meni Uredi
     3.Izabrati podmeni Uredi korisnike
     4. Selektovati opciju „Dodaj“
     5. Popuniti polje prezime sa 2 prezimena (imena), bilo to sa spaceom između ili znakom „-“
     6. Izabrati opciju Korisnik 
     7. Izabrati opciju „Dodaj“

**Comment by dinohurem** [comment]
Ispravljeno u commit-u 6de9ebf1b9d36043b0193ba9c404d2b900752875.
