### ISSUE TITLE
Neaktivnost opcije "Uredi literaturu"

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#39]
Komponenta: Blagajna
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema: 
Prilikom odabira opcije „Uredi literaturu “ iz menija „Uredi“  ne desi se nikakva akcija, niti se ispiše poruka.

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
     2.Izabrati meni Uredi
     3.Izabrati podmeni Uredi literaturu

**Comment by ghost** [comment]
Meni radi, i ostalim radi 
http://pokit.org/get/?05406e28c198cb3c84a22f95619d5e77.jpg
