### ISSUE TITLE
Neaktivnost opcije "Kupi literaturu"

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#41]
Komponenta: Blagajna 

commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema: 
Prilikom odabira opcije „Kupi literaturu“ ne desi se nikakva akcija, niti se ispiše poruka.

Koraci za reproduciranje problema:
      1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
      2. Selektovati željenog studenta
      3.Izabrati opciju Kupi literaturu

**Comment by ghost** [comment]
Nije ništa ispravljano.
1. Slučaj kad je kliknuto a nije selektovan student. http://pokit.org/get/?180fe642b56efec9da4377f8670e7a20.jpg
1. Slučaj kad se selektuje student i klikne na dugme za kupovinu literature
   http://pokit.org/get/?73cdff386bd66cd41887ca7f969dfa42.jpg
