### ISSUE TITLE
Neaktivnost opcije "Dodaj literaturu"

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#42]
Komponenta: Blagajna 

commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa
Opis problema: 
Prilikom odabira opcije „Dodaj literaturu“  ne desi se nikakva akcija, niti se ispiše poruka.

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
      2.Izabrati meni „Dodaj“
     3.Izabrati opciju „Dodaj literaturu“

**Comment by ghost** [comment]
Radilo uvijek: nakon klika, desi se ovo http://pokit.org/get/?8eb991a940b3b8f3e406087f0fdff906.jpg
