### ISSUE TITLE
Neaktivnost opcije "Unesi(studenta)"

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#43]
Komponenta: Unos studenta

commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema: 
Prilikom odabira opcije „Unesi“ na komponenti „Unos studenta“, ne desi se nikakva akcija,niti se ispiše poruka.

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
      2.Izabrati meni „Dodaj“
     3.Izabrati opciju „Dodaj studenta“
     4. Izabrati opciju „Unesi“

**Comment by ghost** [comment]
Nama svima radi
http://pokit.org/get/?cd179f7d3d897b51658f4e365b686c93.jpg
