### ISSUE TITLE
Opcija "Obrisi"

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#44]
Komponente: Korisnici i Blagajna

commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema: 
Opcija „Obrisi“ treba biti napisana kao „Obriši“ zbog konzistentnosti.  

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123 
     2. Na formi "Blagajna" uočava se pomenuta opcija
     3. Odabrati meni Uredi 
    4.Odabrati opciju " Uredi Korisnike"
    5. Otvaranjem forme "Korisnici" uočava se pomenuta opcija

**Comment by dinohurem** [comment]
Ispravljeno u commit-u 6de9ebf1b9d36043b0193ba9c404d2b900752875.
