### ISSUE TITLE
Uređivanje podataka Studenta

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#45]
Komponenta: Unos studenta
commit ID: c7ec3c6fce18e12922654d4900d4a0bb0366b3aa

Opis problema:
Ukoliko se prilikom uređivanja podataka studenta pokušaju promijeniti podaci, nakon potvrde o uspješnim izmjenama kao poruka „iskače “ ispod navedeni excpetion.

Screenshot: http://prntscr.com/79vsqb

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
      2.Selektirati studenta čije podatke treba promijeniti
      3.Odabrati opciju "Detalji/Uredi"
     3.Promijeniti neko polje
     4. Izabrati opciju „Uredi“

**Comment by ghost** [comment]
Ispravljeno

Commit: 8dba45c
