### ISSUE TITLE
Negativna vrijednost skolarine

### ISSUE THREAD

**Issue by AdnanAhmethodzic** [SoftverInzenjeringETFSA/SI2014Tim5#46]
Komponenta: Unos studenta
commit ID: 16c017ff511ecd9580014ee9195badc52a3743b1

Opis problema:
U polje za školarinu je moguće unijeti negativne vrijednosti

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
2.Odabrati opciju Dodaj -> Dodaj Studenta
3.Popuniti sva relevantna polja
4. U polje za školarinu unijeti negativnu vrijednost
5. Izabrati opciju „Unesi“
6. Dobijamo potvrdu da je korisnik unesen

**Comment by ghost** [comment]
Ispravljeno
Commit: 560f716
