### ISSUE TITLE
Pretraga po imenu

### ISSUE THREAD

**Issue by AdnanAhmethodzic** [SoftverInzenjeringETFSA/SI2014Tim5#47]
Komponenta: Unos studenta / Main Window
commit ID: 16c017f

Opis problema:
Student koji se doda se ne pokazuje u glavnom prozoru.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
2.Odabrati opciju Dodaj -> Dodaj Studenta
3.Popuniti sva relevantna polja
4. Izabrati opciju „Unesi“
5. Izabrati opciju "Izađi"
6. U glavnom prozoru, izabrati opciju za pretragu po imenu
7. Unijeti ime novog studenta
8. Student se ne pojavljuje u listi

**Comment by ghost** [comment]
Ispravljeno
Commit: 8ba4989
