### ISSUE TITLE
Kalkulacija ukupnog duga - Glavni prozor

### ISSUE THREAD

**Issue by AdnanAhmethodzic** [SoftverInzenjeringETFSA/SI2014Tim5#49]
Komponenta: Glavni prozor
commit ID: 16c017f

Opis problema: 
Kalkulacija ukupnih dugovanja je pogrešna na glavnom prozoru

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa username: Admin, password: Admin123
2. Izabrati studenta
3. Izabrati opciju Uplate
4. Izračunati vrijednost duga
5. Vratiti se nazad na glavni prozor
6. Vrijednost duga nije tačna 

http://pokit.org/get/?67d421bb66dc7d7aa0740fd012c6ff98.jpg

**Comment by ghost** [comment]
Ispravljeno
Commit: 8ba4989
