### ISSUE TITLE
Unos vise korisnika

### ISSUE THREAD

**Issue by AdnanAhmethodzic** [SoftverInzenjeringETFSA/SI2014Tim5#50]
Komponenta: Unos korisnika
commit ID: 16c017ff511ecd9580014ee9195badc52a3743b1
Opis problema: 
Prilikom unosa korisnika, nakon klika na dugme "Unesi", prozor sa potvrdom se otvori više puta i doda isto toliko novih korisnika sa istim podacima

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
2.Izabrati meni Uredi
3.Izabrati podmeni Uredi korisnike
4. Izabrati opciju „Dodaj“
5. Popuniti formu tačnim podacima
6. Izabrati opciju „Dodaj“
7. Prozor sa potvrdom se pojavljuje više puta
8. Dodalo se više korisnika

**Comment by ghost** [comment]
Ispravljeno 
Commit: 8b1404a

Problem je bio što bi aplikacija ostala raditi i nakon gašenja, pa su bili konflikti kod pristupa bazi
