### ISSUE TITLE
Uredi korisnika - ne prikazuje se korisničko ime

### ISSUE THREAD

**Issue by AdnanAhmethodzic** [SoftverInzenjeringETFSA/SI2014Tim5#51]
Komponenta: Unos korisnika
commit ID: 16c017f
Opis problema: 
Prilikom unosa korisnika, nakon klika na dugme "Unesi", odaberemo opciju "Uredi" unutar istog prozora gdje nam se ne pojavljuje prethodno uneseno korisnicko ime

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
2.Izabrati meni Uredi
3.Izabrati podmeni Uredi korisnike
4. Izabrati opciju „Dodaj“
5. Popuniti formu tačnim podacima
6. Izabrati opciju „Dodaj“
7. Izabrati opciju "Uredi"
8. Nema korisničkog imena

**Comment by dinohurem** [comment]
Popravljeno u commit-u 6de9ebf1b9d36043b0193ba9c404d2b900752875
