### ISSUE TITLE
Pogresno napisane rijeci

### ISSUE THREAD

**Issue by mkenan** [SoftverInzenjeringETFSA/SI2014Tim5#54]
Komponente:
Unos studenta, Dugovanja-Uplate, Blagajna, Izvještaj

commit ID:
16c017ff511ecd9580014ee9195badc52a3743b1

Opis problema:
Neke riječi na formama nisu ispravno napisane, u nekim riječima fali "š" umjesto "s" radi konzistentnosti, na glavnom prozoru je id studenta zapisan kao "ID", a na prozoru Dugovanja-Uplate kao "Id", nije konzistentno.

Screenshot: http://prntscr.com/7aranz ,  http://prntscr.com/7arboz , http://prntscr.com/7arcf2 ,

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa username: Admin, password: Admin123
2. U meniju "Dodaj" odabrati opciju "Dodaj studenta" 
3. Na glavnom prozoru selektovati nekog studenta i odabrati opciju "Uplate"
4. U meniju "Izvještaj" odabrati opciju "Kreiraj izvještaj"

**Comment by ghost** [comment]
Ispravljeno. U Formi za izvještaje to nije greška pošto je enumeracja agregirana u combobox.

**Comment by ghost** [comment]
Commit: 8dba45c
