### ISSUE TITLE
(Ne)Printanje potvrde

### ISSUE THREAD

**Issue by aidagranulo** [SoftverInzenjeringETFSA/SI2014Tim5#55]
Komponenta: Dugovanja-Uplate

commit ID: 57b9839b4cce47f65b9bc2e06b7fbaeee0f7a3c2

Opis problema: Kada se odabere opcija „Printaj potvrdu“ otvara se prazan list papira

Screenshot: http://prntscr.com/7atvf3 

Koraci za reproduciranje problema:
     1.Pokrenuti aplikaciju sa username: Admin, password: Admin123
     2.Izabrati željenog studenta sa liste na formi „Blagajna“
     3.Izabrati opciju „Uplate“
     4. Selektovati određenu ratu
     5. Odabrati opciju „Printaj potvrdu“

**Comment by adautbegovic** [comment]
Nakon izvršavanja navedenih koraka za reproduciranje problema rezultat je bio:
![uplata](https://cloud.githubusercontent.com/assets/11389931/7898258/a163cb1a-06fa-11e5-9ebb-12ff9e66c554.jpg)
