### ISSUE TITLE
Ispis praznog MessageBox-a

### ISSUE THREAD

**Issue by LarisaBesic** [SoftverInzenjeringETFSA/SI2014Tim5#56]
Komponenta: unos korisnika
commit ID: 57b9839b4cce47f65b9bc2e06b7fbaeee0f7a3c2
Opis problema: nakon što se uspješno doda korisnik, sistem prijavljuje odgovarajuću poruku, a potom i prazan MessageBox
Koraci za reproduciranje problema:
1. Unos korisničkog imena i šifre za admina
2. Dodaj -> Dodaj korisnika
3. Unijeti ispravne podatke za korisnika
4. Kliknuti dugme "Dodaj"
Dobijeni rezultat: MessageBox o uspješno dodanom korisniku, a potom i prazan MessageBox (http://pokit.org/get/?1dfba67f718b73b55d53fa4b980c5246.jpg)
Očekivani rezultat: MessageBox o uspješno dodanom korisniku

**Comment by ghost** [comment]
Ispravljeno
Commit: f8e7208
