### ISSUE TITLE
(Ne)slanje mail-a nakon dodavanja novog studenta

### ISSUE THREAD

**Issue by LarisaBesic** [SoftverInzenjeringETFSA/SI2014Tim5#57]
Komponenta: unos studenta
commit ID: 57b9839
Opis problema: nakon što se uspješno doda student, ne izvrši se slanje e-mail-a 
Koraci za reproduciranje problema:
1. Unos korisničkog imena i šifre za korisnika
2. Dodaj -> Dodaj studenta
3. Unijeti ispravne podatke za studenta
4. Kliknuti dugme "Unesi"
Dobijeni rezultat: Poruka o uspješno dodanom studentu, ali slanje mail-a na unesenu e-mail adresu nije izvršeno, kao što je definisano u SRS-u (http://pokit.org/get/?4491edee896af6cfd52adf5e7519ce22.jpg)
Očekivani rezultat: Poruka o uspješno dodanom studentu i slanje mail-a sa generisanom šifrom za studenta

**Comment by ghost** [comment]
To je greška u SRS-u, nema smisla  studentu slat bilo kakvu lozinku.
