### ISSUE TITLE
Moguć unos više studenata sa istim brojem indexa

### ISSUE THREAD

**Issue by LarisaBesic** [SoftverInzenjeringETFSA/SI2014Tim5#58]
Komponenta: unos studenta
commit ID: 57b9839
Opis problema: moguće dodati više studenata sa istim brojem indexa
Koraci za reproduciranje problema:
1. Unos korisničkog imena i šifre za korisnika
2. Dodaj -> Dodaj studenta
3. Unos ispravnih podataka o studentu, pri čemu je broj indexa isti kao i drugom studentu unesenom u bazu
4. Odabit dugmeta "Unesi"
Dobijeni rezultat: Poruka o uspješno dodanom studentu i upis podataka u bazu (http://pokit.org/get/?3cbb3c438eb32c9e656548ef44a3c95c.jpg)
Očekivani rezultat: Poruka o neispravnim podacima (postoji već student sa istim brojem indexa)

**Comment by ghost** [comment]
Ispravljeno, postavljen unique key na tu kolonu u tabeli student u bazi. Provjerava se izuzetak tipa ConstraintViolationException kod unosa ! 

Commit: 4f85a3d
