### ISSUE TITLE
Nemogućnost izmjene šifre za radnika

### ISSUE THREAD

**Issue by LarisaBesic** [SoftverInzenjeringETFSA/SI2014Tim5#60]
Komponenta: promjena lozinke
commit ID: 57b9839
Opis problema: nije moguće izmijeniti šifru za radnika
Koraci za reproduciranje problema:
1. Unos korisničkog imena i šifre za korisnika
2. File -> promijeni lozinku
3. Unos ispravne stare šifre i validne nove
4. Kliknuti na dugme "Promijeni"
Dobijeni rezultat: Poruka o netačnoj staroj šifri (http://pokit.org/get/?cf330c5b1bf1333ae3c52d262e0a8a1e.jpg)
Očekivani rezultat: Poruka o uspješno izmijenjenoj šifri i evidencija iste u bazu

**Comment by adautbegovic** [comment]
Ja zaista nemam ovih problema pri mijenjanju lozinke.
U slikama se vidi rezultat nakon izvršenja navedenih koraka.
![si](https://cloud.githubusercontent.com/assets/11389931/7898226/c59e508c-06f9-11e5-98c6-0be733b4c6b1.jpg)
![si1](https://cloud.githubusercontent.com/assets/11389931/7898227/cb13040e-06f9-11e5-86b4-22c9064bb9b7.jpg)
