### ISSUE TITLE
Moguć unos svih znakova u pretragu studenata 

### ISSUE THREAD

**Issue by LarisaBesic** [SoftverInzenjeringETFSA/SI2014Tim5#61]
Komponenta: Blagajna
commit ID: 57b9839
Opis problema: moguće unijeti sve znakove u polje za pretragu studenata
Koraci za reproduciranje problema:
1. Unos korisničkog imena i šifre za korisnika
2. U polje za pretragu studenta po indexu/dugu za školarinu/dugu za literaturu unijeti slova (npr. "aaa")
3. Kliknuti na dugme "Pretraži"
Dobijeni rezultat: Tabela ostaje ista kao na početku (http://pokit.org/get/?e13c986159f207b99143dd0e5c07ad69.jpg)
Očekivani rezultat: Poruka o neispravno unesenim podacima za pretragu

**Comment by adautbegovic** [comment]
Postoje imena i prezime koja imaju veći broj istih slova zaredom u sebi pa nema razloga da se pojavi poruka o neispravnom unosu.

**Comment by ghost** [comment]
Ispravljeno
Commit: 8ba4989
