### ISSUE TITLE
Nemogućnost dodavanja radnika 

### ISSUE THREAD

**Issue by LarisaBesic** [SoftverInzenjeringETFSA/SI2014Tim5#62]
Komponenta: Unos korisnika
commit ID: 57b9839
Opis problema: Nemoguće dodati korisnika nakon odabira opcije za uređivanje korisnika
Koraci za reproduciranje problema:
1. Unos korisničkog imena i šifre za administratora
2. Uredi -> Uredi korisnike
3. Kliknuti na dugme "Dodaj"
4. Unos ispravne podatke za korisnika
Dobijeni rezultat: Prijava tri poruke o neispravnim podacima 
(http://pokit.org/get/?67090ae4cf9d5fcfd354707f994f110d.jpg)
(http://pokit.org/get/?e93ef7e358d0a4a5c7b35cc6c55fbfa9.jpg)
(http://pokit.org/get/?05d25bad7da5c743097f73c1e0d6f286.jpg)
Očekivani rezultat: Poruka o uspješno dodanom korisniku i evidencija istog u bazu

**Comment by ghost** [comment]
Ispravljeno 
Commit: 8b1404a

Problem je bio što bi aplikacija ostala raditi i nakon gašenja, pa su bili konflikti kod pristupa bazi
