### ISSUE TITLE
Korisnici nisu poredani po abecedi

### ISSUE THREAD

**Issue by LarisaBesic** [SoftverInzenjeringETFSA/SI2014Tim5#63]
Komponenta: Korisnici
commit ID: 57b9839
Opis problema: Korisnici nisu poredani po abedeci
Koraci za reproduciranje problema:
1. Unos korisničkog imena i šifre za administratora
2. Uredi -> Uredi korisnike
Dobijeni rezultat: Korisnici ispisani redoslijedom kojim su dodavani (http://pokit.org/get/?3a19d80e26bda5a83b0199575f010e33.jpg)
Očekivani rezultat: Korisnici ispisani po abecedi kao što je definisano u SRS-u (http://pokit.org/get/?6df4bf2b298b09c15218eb93303acbc8.jpg)

**Comment by dinohurem** [comment]
Popravljeno u commit-u cef7d1cb0b46bf2c203c9a57543ab4825b53b39c.
