### ISSUE TITLE
Nemogućnost pretrage po indeksu

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#64]
Komponenta: Blagajna
commit ID: 5162a429d3

Opis problema: Prilikom odabira opcije pretrage po indeksu, nakon ubacivanja postojeceg indeksa ne izbaci trazenog studenta sa postojecim indeksom.

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Izabrati 'Indeks' na padajucoj listi za pretragu
3. Ukucati postojeci indeks

**Comment by ghost** [comment]
Ispravka
Commit: 8ba4989
http://pokit.org/get/?e457bb706e3753e5a11daa6f01ff4ccd.jpg
