### ISSUE TITLE
Nepostojanje feedback-a za opciju Dodaj studenta 

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#65]
Komponenta: Blagajna
commit ID: 5162a429d3

Opis problema: Prilikom opcije dodavanja novog studenta nema izbacivanje neke poruke ukoliko se nisu popunili svi podaci ili ukoliko postoji neki drugi razlog zasto student nije dodan.

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Izabrati 'Dodaj'-> 'Dodaj Studenta'
3. Ostaviti neka ili sva polja praznim i kliknuti 'Unesi'

**Comment by MerimaKlico** [comment]
Ispravka: Komponenta je 'Unos studenta'

**Comment by ghost** [comment]
Ispravljeno 
Commit: 4692f0e
