### ISSUE TITLE
Izbacivanje greske za validan format JMBG-a

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#66]
Komponenta: Blagajna
commit ID: 5162a42

Opis problema: Prilikom opcije dodavanja novog studenta se izbaci greska za unos JMBG-a sa 13 cifara u vidu poruke 'Problem: Format JMBG-a nije validan'.

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Izabrati 'Dodaj'-> 'Dodaj Studenta'
3. Unijeti 13-cifren broj u JMBG te popuniti ostala polja i klknuti 'Unesi'.

**Comment by MerimaKlico** [comment]
Unijet je broj: 1234567890123

**Comment by MerimaKlico** [comment]
Ispravka: Komponenta je 'Unos studenta'

**Comment by ghost** [comment]
1234567890123 ne može biti validan JMBG, prvih 7 cifara JMBG-a predstavlja datum rođenja u formatu  dd/mm/ggg . Dakle u navedenom broju, osoba je rođena 12-og dana, 34-og mjeseca, 1567-e godine.
