### ISSUE TITLE
Moguce dodavanje vise korisnika sa istim JMBG-om

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#68]
Komponenta: Blagajna
commit ID: 5162a429d3

Opis problema: Prilikom opcije dodavanja korisnika, moguce je dodati vise korisnika sa istim JMBG-om.

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Kliknuti na 'Dodaj', zatim 'Dodaj korisnika'
3. Unijeti validne podatke
4. ponoviti postupak pod 2. i 3. pod uvjetom da je JMBG isti u oba slucaja
5. Kliknuti na 'Dodaj'

**Comment by MerimaKlico** [comment]
Ispravka: Komponenta je 'Unos korisnika'

**Comment by dinohurem** [comment]
Popravljeno u  commit-u 76fb48feeb07a7b19b29b5b1ef0fa2a73beb32e9. I duplicate bug.
