### ISSUE TITLE
Greska kod izbacivanja greske 'Uneseno korisnicko ime vec postoji'

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#69]
Komponenta: Blagajna
commit ID: 5162a429d3

Opis problema: Prilikom opcije dodavanja korisnika, nakon poruke o svakoj gresci se izbacuje i poruka 
'Uneseno korisnicko ime vec postoji' (cak i kada su sva polja prazna!)

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Kliknuti na 'Dodaj', zatim 'Dodaj korisnika'
5. Kliknuti na 'Dodaj'

**Comment by MerimaKlico** [comment]
Ispravka: Komponenta je 'Unos korisnika'

**Comment by dinohurem** [comment]
Moze li malo jasnije, ovaj username i password prije svega nemaju opciju za dodavanje korisnika.

**Comment by ghost** [comment]
Ispravljeno 
Commit: 8b1404a

A stoji da ovaj username i pass nemaju opciju za dodavanje korisnika.
Problem je bio što bi aplikacija ostala raditi i nakon gašenja, pa su bili konflikti kod pristupa bazi
