### ISSUE TITLE
Nepostojanje feedback-a za opciju Detalji/Uredi

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#70]
Komponenta: Blagajna
commit ID: 5162a429d3

Opis problema: Prilikom opcije uredjivanja detalja studenta, nakon neispravno usenenog broja indeksa nema prikaza o gresci.

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Izabrati studenta
3. Kliknuti na 'Detalji/Uredi'
4. U polju broj indeksa ukucati neki tekst
5. Kliknuti 'Uredi'

**Comment by MerimaKlico** [comment]
Ispravka: Komponenta je 'Unos studenta'

**Comment by ghost** [comment]
Ispravljeno
Commit: 4692f0e
