### ISSUE TITLE
Nekonzistentnost izvjestaja 

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#71]
Komponenta: Blagajna
commit ID: 5162a429d3

Opis problema: Prilikom opcije kreiranja izvjestaja, u izvjestaju za troskove studija se prikazu svi studenti, dok u izvjestaju o troskovima za literaturu samo jedan student (iako ni taj jedan student nema troskova za literaturu)

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Kliknuti na Izvjestaj -> Kreiraj izvjestaj
3. Izabrati 'Troskove studija' sa padajuce liste
4. Kliknuti na 'Generisi izvjestaj'
6. Kliknuti na Izvjestaj -> Kreiraj izvjestaj
7. Izabrati 'Troskovi literature' sa padajuce liste
8. Kliknuti na 'Generisi izvjestaj'

**Comment by MerimaKlico** [comment]
Ispravka: Komponenta je 'Izvjestaj'

**Comment by ghost** [comment]
Ako si koristila bazu sa gita, tačno jedan student i ima zaduženu literaturu.
