### ISSUE TITLE
(Ne)Validacija nekih polja prilikom uredjivanja studenta

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#72]
Komponenta: Blagajna
commit ID: 5162a429d3

Opis problema: Prilikom opcije uredjivanja detalja studenta, nakon ostavljenih praznih polja Opcina rodjenja, Drzava rodjenja i Opcina prebivalista, izbacuje se poruka 'Student je uredjen' umjesto greske. Isto se desava i ako u navedenim poljima upisemo samo brojeve.

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: fdzafic, password: Admin123
2. Izabrati studenta
3. Kliknuti na 'Detalji/Uredi'
4. U poljima Opcina rodjenja, Drzava rodjenja i Opcina prebivalista izbrisati podatke ili u njih upisati samo brojeve
5. Kliknuti 'Uredi'

**Comment by MerimaKlico** [comment]
Ispravka: Komponenta je 'Unos studenta'

**Comment by dinohurem** [comment]
Closed adc70da4ce1628809810a3a7ff6729b9136e28fb.
