### ISSUE TITLE
Nemogucnost pokretanje aplikacije kao admin

### ISSUE THREAD

**Issue by MerimaKlico** [SoftverInzenjeringETFSA/SI2014Tim5#73]
Komponenta: Prijava
commit ID: 5162a429d3

Opis problema: Prilikom pokusaja login-a kao admin, sa pristupnim podacima username: Admin te sifrom: Admin123 izbacuje se poruka 'Username je netacan, pokusajte ponovo'

Koraci za reporoduciranje problema:
1. Pokrenuti aplikaciju sa username: Admin, password: Admin123

**Comment by ghost** [comment]
i prije i poslije tebe se prijavljivali sa tim podacima...
